# Test script to verify message avatar functionality
print("=== Message Avatar Test ===")
print("1. Go to: http://127.0.0.1:8000/dashboard/admin-dashboard/chat.html/")
print("2. Select a contact from the left sidebar")
print("3. Check that received messages show:")
print("   - A circular avatar on the left side")
print("   - Avatar should contain contact initials")
print("   - Avatar should have a light gray background")
print("   - Sent messages should NOT show avatars")
print("\nExpected Behavior:")
print("- Received messages: [AVATAR] [Message Content]")
print("- Sent messages: [Message Content] [Status Ticks]")
print("\nWhat was fixed:")
print("- Fixed HTML template structure")
print("- Added CSS with !important declarations")
print("- Ensured proper flex layout")
print("- Added visual enhancements (border, shadow)")
