# Generated by Django 4.2.25 on 2026-01-27 11:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of plan name', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the plan')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='basic', max_length=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_quarterly', models.DecimalField(blank=True, decimal_places=2, help_text='Quarterly price in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_annually', models.DecimalField(blank=True, decimal_places=2, help_text='Annual price in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_biennial', models.DecimalField(blank=True, decimal_places=2, help_text='Biennial price in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('billing_cycles', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('biennial', 'Biennial')], default='monthly', help_text='Available billing cycles for this plan', max_length=20)),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Number of trial days (0 = no trial)', validators=[django.core.validators.MaxValueValidator(365)])),
                ('trial_features', models.JSONField(blank=True, default=dict, help_text='Features available during trial period')),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Maximum number of users allowed (null = unlimited)', null=True)),
                ('max_tickets_per_month', models.PositiveIntegerField(blank=True, help_text='Maximum tickets per month (null = unlimited)', null=True)),
                ('max_agents', models.PositiveIntegerField(blank=True, help_text='Maximum agents allowed (null = unlimited)', null=True)),
                ('storage_limit_gb', models.PositiveIntegerField(blank=True, help_text='Storage limit in GB (null = unlimited)', null=True)),
                ('api_calls_per_month', models.PositiveIntegerField(blank=True, help_text='API calls allowed per month (null = unlimited)', null=True)),
                ('features', models.JSONField(blank=True, default=dict, help_text='Plan features as key-value pairs')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular plan')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which plans are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as key-value pairs')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('feature_type', models.CharField(choices=[('boolean', 'Boolean'), ('number', 'Number'), ('text', 'Text'), ('list', 'List')], default='boolean', max_length=20)),
                ('default_value', models.JSONField(blank=True, default=None)),
                ('icon', models.CharField(blank=True, help_text='Icon class name', max_length=50)),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_premium', models.BooleanField(default=False, help_text='Mark as premium feature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trial'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('expired', 'Expired')], default='unpaid', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PlanFeatureMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=None, help_text='Feature value for this plan')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planfeature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_mappings', to='core.plan')),
            ],
            options={
                'verbose_name': 'Plan Feature Mapping',
                'verbose_name_plural': 'Plan Feature Mappings',
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['status', 'plan_type'], name='core_plan_status_fff732_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_popular', 'sort_order'], name='core_plan_is_popu_d00838_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subscription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='planfeaturemapping',
            unique_together={('plan', 'feature')},
        ),
    ]
