# Generated by Django 4.2.25 on 2025-11-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('website_url', models.URLField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('default_language', models.CharField(blank=True, default='English (United States)', max_length=50)),
                ('time_zone', models.CharField(blank=True, default='UTC', max_length=50)),
                ('date_format', models.CharField(blank=True, default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(blank=True, default='24-hour', max_length=20)),
                ('first_day_of_week', models.IntegerField(blank=True, default=1)),
                ('currency', models.CharField(blank=True, default='USD - US Dollar ($)', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('user_registration', models.BooleanField(default=True)),
                ('email_verification', models.BooleanField(default=True)),
                ('remember_me', models.BooleanField(default=True)),
                ('show_tutorial', models.BooleanField(default=True)),
                ('theme', models.CharField(blank=True, default='light', max_length=10)),
                ('primary_color', models.CharField(blank=True, default='#0d6efd', max_length=7)),
                ('fixed_header', models.BooleanField(default=True)),
                ('fixed_sidebar', models.BooleanField(default=True)),
                ('collapsed_sidebar', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
