# Generated by Django 4.2.25 on 2025-11-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_ticket_reopen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_ticket_assignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_ticket_priority',
            field=models.CharField(blank=True, default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_ticket_status',
            field=models.CharField(blank=True, default='Open', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='first_response_hours',
            field=models.IntegerField(blank=True, default=24),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resolution_time_hours',
            field=models.IntegerField(blank=True, default=72),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sla_business_hours',
            field=models.CharField(blank=True, default='Business Hours (9 AM - 5 PM, Mon-Fri)', max_length=100),
        ),
    ]
