# Generated by Django 4.2.25 on 2026-04-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_create_notification_table'),
    ]

    operations = [
    ]
