# Generated by Django 4.2.25 on 2025-12-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Agent', 'Agent'), ('User', 'User')], max_length=50, unique=True),
        ),
    ]
