# Generated by Django 4.2.25 on 2026-02-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_date_of_birth_userprofile_gender_and_more'),
        ('users', '0006_userprofile_date_of_birth_userprofile_gender'),
    ]

    operations = [
    ]
