# Generated by Django 4.2.25 on 2026-04-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_rename_users_plan_tickets'),
        ('users', '0009_userprofile_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.company'),
        ),
    ]
