# Generated by Django 4.2.25 on 2025-11-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_userrating_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
