# Generated by Django 4.2.25 on 2025-11-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_first_response_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='first_response_at',
        ),
    ]
