# Generated by Django 4.2.25 on 2025-12-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
