# Generated by Django 4.2.25 on 2025-12-31 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_orderitem_order_ticket_company_delete_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='company',
        ),
    ]
