# Generated by Django 4.2.25 on 2026-04-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('General', 'General'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
