# Generated by Django 4.2.25 on 2026-04-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='custom_category',
            field=models.CharField(blank=True, help_text="Custom category when 'Other' is selected", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('General', 'General'), ('Support', 'Support'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
