# Generated by Django 4.2.25 on 2026-04-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticket_custom_category_alter_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='custom_category',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('General', 'General'), ('Support', 'Support'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
