# Generated by Django 4.2.25 on 2026-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_add_support_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='channel',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Chat', 'Chat'), ('Web', 'Web')], default='Web', max_length=20, null=True),
        ),
    ]
