# Generated by Django 4.2.25 on 2026-04-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_rename_users_plan_tickets'),
        ('tickets', '0021_ticket_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_set', to='superadmin.plan'),
        ),
    ]
