# Generated by Django 4.2.25 on 2025-12-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
