# Generated by Django 4.2.25 on 2025-12-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.plan'),
        ),
        migrations.AddField(
            model_name='company',
            name='plan_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('trial', 'Trial'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
    ]
