# Generated by Django 4.2.25 on 2025-12-29 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0006_order_product_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=100)),
                ('profile_email', models.EmailField(blank=True, max_length=254)),
                ('profile_phone', models.CharField(blank=True, max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('team', 'Team Only')], default='public', max_length=20)),
                ('dark_mode', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', max_length=5)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('EST', 'Eastern Time'), ('PST', 'Pacific Time'), ('IST', 'India Standard Time'), ('CET', 'Central European Time'), ('JST', 'Japan Standard Time')], default='UTC', max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('INR', 'Indian Rupee (₹)')], default='USD', max_length=3)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('user_registration', models.BooleanField(default=True)),
                ('email_verification', models.BooleanField(default=True)),
                ('remember_me', models.BooleanField(default=True)),
                ('show_tutorial', models.BooleanField(default=True)),
                ('default_ticket_status', models.CharField(default='Open', max_length=50)),
                ('default_ticket_priority', models.CharField(default='Medium', max_length=20)),
                ('auto_ticket_assignment', models.BooleanField(default=True)),
                ('allow_ticket_reopen', models.BooleanField(default=True)),
                ('first_response_hours', models.IntegerField(default=24)),
                ('resolution_time_hours', models.IntegerField(default=72)),
                ('sla_business_hours', models.CharField(default='Business Hours (9 AM - 5 PM, Mon-Fri)', max_length=100)),
                ('theme', models.CharField(default='light', max_length=10)),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('fixed_header', models.BooleanField(default=True)),
                ('fixed_sidebar', models.BooleanField(default=True)),
                ('collapsed_sidebar', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('website_url', models.URLField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
