# Generated by Django 4.2.25 on 2026-01-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_role_name'),
        ('superadmin', '0009_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='companies', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='superadminsettings',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('INR', 'Indian Rupee (₹)')], default='INR', max_length=3),
        ),
    ]
