# Generated by Django 4.2.25 on 2026-04-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_add_professional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadminsettings',
            name='collapsed_logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superadminsettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
