# Generated by Django 4.2.25 on 2026-04-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_superadminsettings_collapsed_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='users',
            new_name='tickets',
        ),
    ]
