# Generated by Django 4.2.25 on 2026-04-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_rename_users_plan_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
